## Draws Venn diagrams for A, B, C 
## requires the table generated by A_vs_B_vs_C_overlap function

triple.venn.prot = function(comparison_table, scaled = TRUE){

#area.vector2 = c(comparison_table[1,paste(comparison_table$A,"_exclusively", sep ="")],
#                  comparison_table[1,paste(comparison_table$A,"_and_", comparison_table$B, sep ="")] - comparison_table[1,paste(comparis#on_table$A,"_and_", comparison_table$B, "_and_", comparison_table$C, sep ="")],
#                  comparison_table[1,paste(comparison_table$B,"_exclusively", sep ="")],
#                  comparison_table[1,paste(comparison_table$A,"_and_", comparison_table$C, sep ="")] - comparison_table[1,paste(comparis#on_table$A,"_and_", comparison_table$B, "_and_", comparison_table$C, sep ="")],
#                  comparison_table[1,paste(comparison_table$A,"_and_", comparison_table$B, "_and_", comparison_table$C, sep ="")],
#                  comparison_table[1,paste(comparison_table$B,"_and_", comparison_table$C, sep ="")] - comparison_table[1,paste(comparison_table$A,"_and_", comparison_table$B, "_and_", comparison_table$C, sep ="")],
#                  comparison_table[1,paste(comparison_table$C,"_exclusively", sep ="")])

  
if(scaled == TRUE){
venn.d = draw.triple.venn(area1 = comparison_table[1,paste("count_",comparison_table$A, sep ="")], 
                          area2 = comparison_table[1,paste("count_",comparison_table$B, sep ="")], 
                          area3 = comparison_table[1,paste("count_",comparison_table$C, sep ="")], 
                          n12 = comparison_table[1,paste(comparison_table$A,"_and_", comparison_table$B, sep ="")], 
                          n23 = comparison_table[1,paste(comparison_table$B,"_and_", comparison_table$C, sep ="")],
                          n13 = comparison_table[1,paste(comparison_table$A,"_and_", comparison_table$C, sep ="")],
                          n123 = comparison_table[1,paste(comparison_table$A,"_and_", comparison_table$B, "_and_", comparison_table$C, sep ="")], 
                          category = c(comparison_table$A, 
                                       comparison_table$B, 
                                       comparison_table$C), 
                          lty = rep("blank", 3), 
                          fill = c("blue", "red", "green"), 
                          alpha = rep(0.5, 3), cat.pos = c(350, 25, 160), 
                          cat.dist = c(0.08,0.035, 0.08), 
                          cat.cex = c(0.9,0.9, 0.9), scaled = TRUE, euler.d = TRUE,  margin = 0.05,
                          #overrideTriple = 1,
                          #direct.area = TRUE,
                          #area.vector = area.vector2,
                          cex = 0.8
)
}

if(scaled == FALSE){
    venn.d = draw.triple.venn(area1 = comparison_table[1,paste("count_",comparison_table$A, sep ="")], 
                              area2 = comparison_table[1,paste("count_",comparison_table$B, sep ="")], 
                              area3 = comparison_table[1,paste("count_",comparison_table$C, sep ="")], 
                              n12 = comparison_table[1,paste(comparison_table$A,"_and_", comparison_table$B, sep ="")], 
                              n23 = comparison_table[1,paste(comparison_table$B,"_and_", comparison_table$C, sep ="")],
                              n13 = comparison_table[1,paste(comparison_table$A,"_and_", comparison_table$C, sep ="")],
                              n123 = comparison_table[1,paste(comparison_table$A,"_and_", comparison_table$B, "_and_", comparison_table$C, sep ="")], 
                              category = c(comparison_table$A, 
                                           comparison_table$B, 
                                           comparison_table$C), 
                              lty = rep("blank", 3), 
                              fill = c("blue", "red", "green"), 
                              alpha = rep(0.5, 3), cat.pos = c(0, 45, 160), 
                              cat.dist = c(0.035,0.035, 0.08), 
                              cat.cex = c(0.9,0.9, 0.9), scaled = T, euler.d = T,  margin = 0.05,
                              cex = 0.8
                          
    )
}

}